### ISSUE TITLE
support multi-golden tests in a single test

### ISSUE THREAD

**Issue by amrgetment** [mjablecnik/adaptive_golden_test#2]
if I run two `expectGolden` tests I will get this error
`Reentrant call to runAsync() denied
`
 can you support multi-golden tests in a single test?

**Comment by mjablecnik** [comment]
Could you create some example project where I can check it?

**Comment by amrgetment** [comment]
@mjablecnik you already have multi-golden testing in the example folder just run `flutter test --update-goldens` 
the example folder is here
https://github.com/StorybookToolkit/adaptive_golden_test/tree/main/example/simple_app

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/a5d45db3-984c-4802-b856-bd6b459a4e06" />

**Comment by mjablecnik** [comment]
Ok, I see the problem what is there. I fixed and pushed it into repository. 
Could you check if simple_app tests work right for you now?

**Comment by amrgetment** [comment]
thanks a lot, it works fine now
thanks for your effort
